import type { Brand, Category } from "@/types/content";

export const categories: Category[] = [
  {
    slug: "face-care",
    title: "Уход за лицом",
    description: "Кремы, гели, гидролаты и мягкое очищение для ежедневного ухода.",
  },
  {
    slug: "body-care",
    title: "Уход за телом",
    description: "Натуральные средства для душа, питания, восстановления и комфорта кожи.",
  },
  {
    slug: "hair-care",
    title: "Уход за волосами",
    description: "Шампуни, бальзамы и уходовые формулы для разных типов волос.",
  },
  {
    slug: "oral-care",
    title: "Уход за полостью рта",
    description: "Зубные пасты и ополаскиватели без агрессивных компонентов.",
  },
  {
    slug: "vitamins-and-supplements",
    title: "Витамины и БАДы",
    description: "Витаминные комплексы, нутрицевтики, пробиотики, спирулина и натуральные тоники для ежедневной поддержки.",
  },
  {
    slug: "essential-oils",
    title: "Эфирные масла",
    description: "Ароматерапия, органические эфирные масла, смеси и гидролаты.",
  },
  {
    slug: "decorative-cosmetics",
    title: "Декоративная косметика",
    description: "Минеральная и натуральная декоративная косметика, аксессуары.",
  },
  {
    slug: "hair-color",
    title: "Краски для волос",
    description: "Деликатное окрашивание и уход за волосами после окрашивания.",
  },
  {
    slug: "children",
    title: "Для детей",
    description: "Бережный уход и профилактические продукты для семьи и детей.",
  },
  {
    slug: "vegan",
    title: "Для веганов",
    description: "Продукты без компонентов животного происхождения.",
  },
  {
    slug: "accessories",
    title: "Аксессуары",
    description: "Бьюти-аксессуары, щетки, массажные и уходовые принадлежности.",
  },
  {
    slug: "feet-care",
    title: "Для ног",
    description: "Кремы, спреи и восстанавливающий уход для стоп и ногтей.",
  },
  {
    slug: "deodorants",
    title: "Дезодоранты",
    description: "Современные формулы ежедневной свежести без лишней агрессии к коже.",
  },
  {
    slug: "sets",
    title: "Наборы",
    description: "Подарочные и сезонные комплекты для ухода, ароматерапии и макияжа.",
  },
  {
    slug: "books",
    title: "Книги и справочники",
    description: "Печатные и электронные материалы Арнебии для покупателей и специалистов.",
  },
];

export const brands: Brand[] = [
  {
    slug: "arnebia-books",
    title: "Издательство Арнебия",
    latin: "Arnebia Books",
    short: "Книги и профессиональные издания по натуропатии, питанию, рефлексотерапии, фитотерапии и здоровью.",
    description:
      "Книжное направление Арнебии: переводные и авторские издания для специалистов и читателей, которым важен внимательный, доказательный и практичный подход к теме здоровья.",
    origin: "Россия",
    focus: ["Книги", "Справочники", "Рефлексотерапия", "Натуропатия"],
    image: "/references/arnebia-general-catalog.jpg",
    logoImage: "/brand/logos/arnebia-books-logo.png",
    flagCodes: ["ru"],
    logoText: "АРНЕБИЯ",
    logoSubtext: "books & guides",
    accent: "#a8673f",
  },
  {
    slug: "villaphyta",
    title: "Виллафита",
    latin: "Villaphyta",
    short: "Эфирные масла, гидролаты, БАДы и современная натуральная косметика.",
    description:
      "Собственный бренд Арнебии с фокусом на природные активы, ароматерапию и ежедневный уход для всей семьи.",
    origin: "Франция / Россия",
    focus: ["Гидролаты", "Эфирные масла", "БАДы", "Уход за волосами"],
    image: "https://www.arnebia.ru/img/shop/4306b.jpg",
    logoImage: "/brand/logos/villaphyta-logo.png",
    flagCodes: ["ru"],
    logoText: "VILLAPHYTA",
    logoSubtext: "натуральный уход",
    accent: "#178744",
    featured: true,
  },
  {
    slug: "arnebia-selection",
    title: "Арнебия Селекшн",
    latin: "Arnebia Selection",
    short: "Доступная инновационная дерматокосметика из России.",
    description:
      "Линия ухода с мочевиной, гиалуроновой кислотой и современными комплексами для сухой, чувствительной и требовательной кожи.",
    origin: "Россия",
    focus: ["Дерматокосметика", "Уход за лицом", "Уход за руками", "Уход за стопами"],
    image: "https://www.arnebia.ru/img/shop/4333b.jpg",
    logoImage: "/brand/logos/arnebia-selection-logo.png",
    flagCodes: ["ru", "de"],
    logoText: "АРНЕБИЯ SELECTION",
    logoSubtext: "derma care",
    accent: "#7b6b56",
    featured: true,
  },
  {
    slug: "arnebia-vitamins",
    title: "Витамины Арнебия",
    latin: "Arnebia Vitamins",
    short: "Шипучие витаминно-минеральные комплексы для ежедневной поддержки организма.",
    description:
      "Линейка витаминов и минералов Арнебия в удобном формате шипучих таблеток: витамин C, цинк, селен, кальций, магний и мультивитаминные комплексы.",
    origin: "Германия",
    focus: ["Витамины", "Минералы", "Ежедневная поддержка"],
    image: "https://www.arnebia.ru/img/shop/1317f.jpg",
    logoImage: "/brand/logos/arnebia-vitamins-logo.png",
    flagCodes: ["de"],
    logoText: "АРНЕБИЯ",
    logoSubtext: "витамины и минералы",
    accent: "#9a7b35",
    featured: true,
  },
  {
    slug: "atlantomarin",
    title: "Атлантомарин",
    latin: "Atlantomarin",
    short: "Уход за полостью рта со спирулиной и минеральными комплексами.",
    description:
      "Пасты и ополаскиватели для ежедневной профилактики, свежего дыхания и бережной защиты десен.",
    origin: "Россия",
    focus: ["Ополаскиватели", "Зубные пасты", "Минералы", "Спирулина"],
    image: "https://www.arnebia.ru/img/shop/4413b.jpg",
    logoImage: "/brand/logos/atlantomarin-logo.png",
    flagCodes: ["ru"],
    logoText: "АТЛАНТОМАРИН",
    logoSubtext: "oral care",
    accent: "#4f9a99",
    featured: true,
  },
  {
    slug: "benecos",
    title: "Бенекос",
    latin: "Benecos",
    short: "Натуральная декоративная косметика и аксессуары.",
    description:
      "Демократичная европейская линия макияжа с натуральной эстетикой и понятными ежедневными продуктами.",
    origin: "Германия",
    focus: ["Макияж", "Аксессуары", "Минеральные текстуры"],
    image: "https://www.arnebia.ru/img/shop/2225b.jpg",
    logoImage: "/brand/logos/benecos-logo.png",
    flagCodes: ["de"],
    logoText: "benecos",
    logoSubtext: "natural beauty",
    accent: "#b06b7c",
  },
  {
    slug: "primavera",
    title: "Примавера",
    latin: "Primavera Life",
    short: "Натуральная аромакосметика и эфирные масла.",
    description:
      "Ароматерапевтическая экспертиза, органическое сырье и формулы для эмоционального и телесного баланса.",
    origin: "Германия",
    focus: ["Аромакосметика", "Эфирные масла", "SPA"],
    image: "https://www.arnebia.ru/img/shop/2359b.jpg",
    logoImage: "/brand/logos/primavera-logo.png",
    flagCodes: ["de"],
    logoText: "PRIMAVERA",
    logoSubtext: "pure nature",
    accent: "#8f8643",
  },
  {
    slug: "herbatint",
    title: "Гербатинт",
    latin: "Herbatint",
    short: "Краски и уход за волосами с мягким подходом к окрашиванию.",
    description:
      "Линия для окрашивания и поддерживающего ухода, созданная для клиентов, которым важна деликатность формул.",
    origin: "Италия",
    focus: ["Краски для волос", "Уход после окрашивания"],
    image: "https://www.arnebia.ru/img/shop/3620b.jpg",
    logoImage: "/brand/logos/herbatint-logo.png",
    flagCodes: ["it"],
    logoText: "HERBATINT",
    logoSubtext: "color care",
    accent: "#48734a",
  },
  {
    slug: "sanatur",
    title: "Санатур",
    latin: "Sanatur",
    short: "БАДы со спирулиной и нутрицевтические продукты.",
    description:
      "Немецкая линия нутрицевтиков на основе спирулины и природных компонентов для осознанной поддержки организма.",
    origin: "Германия",
    focus: ["Спирулина", "Нутрицевтики", "БАДы"],
    image: "https://www.arnebia.ru/img/shop/3060b.jpg",
    logoImage: "/brand/logos/sanatur-logo.png",
    flagCodes: ["de"],
    logoText: "SANATUR",
    logoSubtext: "spirulina & phyto",
    accent: "#178744",
  },
  {
    slug: "erboristeria",
    title: "Эрбористериа Маджентина",
    latin: "Erboristeria Magentina",
    short: "Холистическая натуральная косметика из Италии.",
    description:
      "Фитобальзамы, эфирные масла и уходовые продукты, вдохновленные традициями итальянских травников.",
    origin: "Италия",
    focus: ["Фитобальзамы", "Эфирные масла", "Холистический уход"],
    image: "https://www.arnebia.ru/img/shop/3595b.jpg",
    logoImage: "/brand/logos/erboristeria-magentina-logo.png",
    flagCodes: ["it"],
    logoText: "ERBORISTERIA MAGENTINA",
    logoSubtext: "erbe e natura",
    accent: "#6f804a",
  },
  {
    slug: "florame",
    title: "Флорам",
    latin: "Florame",
    short: "Натуральная косметика и ароматерапия.",
    description:
      "Европейский бренд с фокусом на органические ингредиенты, уходовые текстуры и ароматерапевтические решения.",
    origin: "Франция",
    focus: ["Натуральная косметика", "Ароматерапия"],
    image: "https://www.arnebia.ru/img/shop/3645b.jpg",
    logoImage: "/brand/logos/florame-logo.png",
    flagCodes: ["fr"],
    logoText: "FLORAME",
    logoSubtext: "aromathérapie",
    accent: "#4f9a73",
  },
  {
    slug: "foersters",
    title: "Фёрстерс",
    latin: "Foerster's",
    short: "Бьюти-аксессуары для ухода и массажа.",
    description:
      "Щетки, массажные аксессуары и практичные инструменты для ежедневных ритуалов ухода.",
    origin: "Германия",
    focus: ["Аксессуары", "Массаж", "Уход за телом"],
    image: "https://www.arnebia.ru/img/shop/1612b.jpg",
    logoImage: "/brand/logos/foersters-logo.png",
    flagCodes: ["de"],
    logoText: "FÖRSTER'S",
    logoSubtext: "natural brushes",
    accent: "#a36c3b",
  },
];

export function getBrand(slug: string) {
  return brands.find((brand) => brand.slug === slug);
}

export function getCategory(slug: string) {
  return categories.find((category) => category.slug === slug);
}
